### ISSUE TITLE
Could not pass "ItemUseHandler" for CropSeed - 'GN_AVOCADO_PIT'

### ISSUE THREAD

**Issue by HiTech0926** [SlimefunGuguProject/Gastronomicon#11]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/Gastronomicon/issues)，且没有找到相同的问题

### 问题描述

Paper1.19.4环境，Slimefun2023.06发行版本，Gastronomicon vBuild 7 (git 38ba535)版本
在特定操作下发生报错，并且刷屏：[https://paste.guizhanss.net/ixnFB](https://paste.guizhanss.net/ixnFB)

### 复现步骤

1.安装附属和Slimefun2023.06发行版本，不做任何附属更改
2.正常游玩，等待报错

### 预期行为

可能是GN_AVOCADO_PIT物品/机器在使用时候出现的代码错误

### 服务器日志

https://paste.guizhanss.net/ixnFB

### 错误报告

https://paste.guizhanss.net/Ixpxd

### 服务端软件

Paper

### Minecraft 版本

1.19.4

### Slimefun版本

[10:01:45 INFO]: Slimefun 运行的服务器环境:
Paper git-Paper-550 (MC: 1.19.4)
Slimefun 2023.06-release
Metrics-组件 #29
Java 17

### 插件版本

7

**Comment by ybw0014** [comment]
你这错误报告还是Cultivation的
